services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: astro-docker-demo-dynamic:latest
    container_name: astro-docker-demo-dynamic
    ports:
      - "4321:4321"
    restart: unless-stopped
